server:
  port: 8010

spring:
  application:
    name: danmaku-sender

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/baswebsite?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = Asia/Shanghai
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 10
      minimum-idle: 2
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5s
  servlet:
    multipart:
     max-file-size: 100MB
     max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hikari.danmaku.entity

logging:
  level:
    root: info


api:
  dmPost: http://api.bilibili.com/x/v2/dm/post
